# Generated by Django 5.2.7 on 2025-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='long_url',
            new_name='original_url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='url',
            name='short_code',
        ),
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='short_id',
            field=models.CharField(default='xxx', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
